# Generated by Django 6.1.1 on 2026-09-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('Burger', 'Burger'), ('Pizza', 'Pizza'), ('Indian', 'Indian'), ('Chinese', 'Chinese'), ('Drinks', 'Drinks'), ('Dessert', 'Dessert')], max_length=50)),
                ('image', models.URLField(blank=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
